# Generated by gen_sym.py from flashop_m7.elf -- do not edit.
# blob: 612 bytes, sha256[:16] 47fbf53de68a7e0f
# Offsets are relative to the link base; flashos.tcl adds the base
# for whichever core the algorithm was loaded under. The Thumb bit is
# applied there, not here.

set FLASHPRG_BLOB_SIZE 612
set FLASHPRG_OFF_Init         0x0
set FLASHPRG_OFF_UnInit       0x16C
set FLASHPRG_OFF_EraseChip    0x2C
set FLASHPRG_OFF_EraseSector  0x5C
set FLASHPRG_OFF_EraseRange   0x88
set FLASHPRG_OFF_ProgramPage  0xE8
set FLASHPRG_OFF_Verify       0x130
set FLASHPRG_OFF_FlashSum     0x210

# Not called by flashos.tcl; listed so the layout is visible.
set FLASHPRG_OFF_CheckSts     0x170
set FLASHPRG_OFF_Delay500ms   0x20E
